classdef MotionPlan < robotics.ros.Message
    %MotionPlan MATLAB implementation of car_msgs/MotionPlan
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'car_msgs/MotionPlan' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '9ff6ef695ee5a50626d567f8f9bb90d5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        CarMsgsReferenceClass = robotics.ros.msg.internal.MessageFactory.getClassForType('car_msgs/Reference') % Dispatch to MATLAB class for message type car_msgs/Reference
    end
    
    properties (Dependent)
        RefArray
    end
    
    properties (Access = protected)
        Cache = struct('RefArray', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'RefArray'} % List of non-constant message properties
        ROSPropertyList = {'refArray'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MotionPlan(msg)
            %MotionPlan Construct the message object MotionPlan
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function refarray = get.RefArray(obj)
            %get.RefArray Get the value for property RefArray
            if isempty(obj.Cache.RefArray)
                javaArray = obj.JavaMessage.getRefArray;
                array = obj.readJavaArray(javaArray, obj.CarMsgsReferenceClass);
                obj.Cache.RefArray = feval(obj.CarMsgsReferenceClass, array);
            end
            refarray = obj.Cache.RefArray;
        end
        
        function set.RefArray(obj, refarray)
            %set.RefArray Set the value for property RefArray
            if ~isvector(refarray) && isempty(refarray)
                % Allow empty [] input
                refarray = feval([obj.CarMsgsReferenceClass '.empty'], 0, 1);
            end
            
            validateattributes(refarray, {obj.CarMsgsReferenceClass}, {'vector'}, 'MotionPlan', 'RefArray');
            
            javaArray = obj.JavaMessage.getRefArray;
            array = obj.writeJavaArray(refarray, javaArray, obj.CarMsgsReferenceClass);
            obj.JavaMessage.setRefArray(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.RefArray)
                obj.Cache.RefArray = [];
                obj.Cache.RefArray = obj.RefArray;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.RefArray = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.RefArray = copy(obj.RefArray);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            RefArrayCell = arrayfun(@(x) feval([obj.CarMsgsReferenceClass '.loadobj'], x), strObj.RefArray, 'UniformOutput', false);
            obj.RefArray = vertcat(RefArrayCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RefArray = arrayfun(@(x) saveobj(x), obj.RefArray);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.car_msgs.MotionPlan.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.car_msgs.MotionPlan;
            obj.reload(strObj);
        end
    end
end
